export class Routing {
  static checkout = 'checkout';
  static shipping = 'shipping';
  static payment = 'payment';
  static basket = 'basket';
  static blogs = 'blogs';
  static category = 'category';
  static register = 'register';
  static product = 'product';
  static wallet = 'wallet';
  static profile = 'profile';
  static orders = 'orders';
  static favorites = 'favorites';
  static returnedRequests = 'returned-requests';
  static address = 'address';
  static personalInfo = 'personal-info';
  static comments = 'comments';
  static myBox = 'my-box';
  static credits = 'credits';
  static callback = 'callback';
  static notFound = 'not-found';
}
